---

#
# Our vagrant test host
#
- hosts: vagrant
  user: vagrant
  sudo: yes
  vars:
     #
     # The default key that Vagrant uses
     #
     ssh_key: ~/.vagrant.d/insecure_private_key 
  roles: 
    - update
    - common
    - timezone
    - { role: user, username: "ubuntu" }
    - { role: btsync, user: "ubuntu", tags: "btsync" }
    - { role: splunk, user: "vagrant", tags: "splunk" }

#
# Production  hosts
# These should be Ubuntu 12.04 x64
#
- hosts: production
  user: root
  sudo: yes
  vars:
     #
     # Replace this ssh key with one for your own $HOME/.ssh/ directory...
     #
     ssh_key: digitalocean-dmuth.org.pub
  roles: 
    - update
    - common
    #
    # Create an ubuntu user.  Digital Ocean distros don't have this,
    # but this isn't part of the DO-specific role, since other cloud
    # providers may have similar "FrankenLinux" images.
    #
    - { role: user, username: "ubuntu" }
    - timezone
    - { role: btsync, user: "ubuntu", tags: "btsync" }
    #
    # Digital Ocean specific things, such as setting up a swap file
    #
    - { role: provider-digital-ocean, tags: "provider" }



